### PR TITLE
Teams

### PR DESCRIPTION
**Pull request by cltweedie**
Implemented the teams resource of the bitbucket API.

### CODE REVIEW

**Comment by dmgarland** [comment]
@cltweedie could you squash your commits and I'll merge in. Ta!

**Comment by jakobdamjensen** [comment]
@cltweedie Do you need any help to do this?

**Comment by alwyn** [comment]
Hi guys,

Can you perhaps bring this in?  @cltweedie  hasn't been active on github since May, maybe something is wrong.  Hopefully life just got in the way.

**Comment by dmgarland** [comment]
I'll see about taking this on and getting this merged in this weekend. Thanks for your patience

**Pull request merged**
