### PR TITLE
Add Unit Tests

### PR DESCRIPTION
**Pull request by rashmirathi1729**

### CODE REVIEW

**Comment by dmgarland** [comment]
@cltweedie @rashmirathi1729 @alfredoliverwillder this is turning into a bit of a monster... I'm expecting only additions to the spec folder but I'm seeing changes to lib in here too. Why has lib changed and can we separate this out?

**Comment by cltweedie** [comment]
That's probably my fault! I may have got a bit overzealous with fixing things while implementing tests.

**Comment by dmgarland** [comment]
It's OK ... try moving this into another branch and rebasing off of master... step through and skip anything that touches lib... then send a separate PR for the changes your making to lib

**Comment by dmgarland** [comment]
Merged in #58

**Pull request closed without merging**
