### PR TITLE
Adding unit tests

### PR DESCRIPTION
**Pull request by alfredoliverwillder**

### CODE REVIEW

**Comment by dmgarland** [comment]
Hi @alfredoliverwillder and @rashmirathi1729 thanks for sending these. Could you please fix the merge conflicts and push up?

**Comment by rashmirathi1729** [comment]
@dmgarland Done

**Comment by rashmirathi1729** [comment]
@dmgarland This pull request is now obsolete beacause of https://github.com/bitbucket-rest-api/bitbucket/pull/52. Can you close this pull request without merging it?

**Comment by dmgarland** [comment]
Alright matey

**Pull request closed without merging**
