### PR TITLE
Renamed Repos::Sources#get to #list as it returns a list of files

### PR DESCRIPTION
**Pull request by ispyropoulos**
Added a new `Repos::Sources#get` method, which returns the raw
contents of an individual file.

### CODE REVIEW

**Comment by dmgarland** [comment]
Was there a test for this or does it pass all the tests?

**Comment by ispyropoulos** [comment]
It passes all tests, but no ones have been added. I had written this before there was any test suite in this project. I had add some though.

**Comment by ispyropoulos** [comment]
I added some very basic specs, according to the existing examples.

**Comment by ispyropoulos** [comment]
Any chance of merging this?

**Pull request merged**
